name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm run test

    - name: Run linter
      run: npm run lint

    - name: Build application
      run: npm run build

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker to use gcloud as credential helper
      run: gcloud auth configure-docker

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy excalidraw-nextjs \
          --source . \
          --region us-central1 \
          --allow-unauthenticated \
          --set-env-vars FASTAPI_URL=${{ secrets.FASTAPI_URL }} \
          --platform managed \
          --memory 1Gi \
          --cpu 1 \
          --min-instances 0 \
          --max-instances 10 \
          --port 3000

    - name: Get service URL
      run: |
        SERVICE_URL=$(gcloud run services describe excalidraw-nextjs --region=us-central1 --format='value(status.url)')
        CUSTOM_DOMAIN="https://excalidraw.paulbonneville.com"
        echo "Deployed to Cloud Run: $SERVICE_URL"
        echo "Custom domain: $CUSTOM_DOMAIN"
        echo "SERVICE_URL=$SERVICE_URL" >> $GITHUB_ENV
        echo "CUSTOM_DOMAIN=$CUSTOM_DOMAIN" >> $GITHUB_ENV

    - name: Test deployment
      run: |
        # Wait a moment for deployment to be ready
        sleep 10
        # Test Cloud Run service directly
        curl -f "$SERVICE_URL" || exit 1
        # Test custom domain
        curl -f "$CUSTOM_DOMAIN" || exit 1
        echo "✅ Both Cloud Run service and custom domain are responding"